# Apply the below kubernetes secret before you apply the ProviderConfig
apiVersion: v1
kind: Secret
metadata:
  name: example-provider-secret
  namespace: crossplane-system
stringData:
  test-key: "" #Example: "-----BEGIN PRIVATE KEY-----\nMIIE..."

---
apiVersion: myplayground.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: test-key
