apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: sample-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: sample-namespace-3
        labels:
          akshay: "becky"
  providerConfigRef:
    name: kubernetes-provider
